## Just some basic EDA and a how-to guide. ##

In [49]:
import re
import os

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

# "magic" command to make plots show up in the notebook
%matplotlib inline 

filepath = '../input/'

Kaggle changed they way they handle compressed files sometime in 2018.  They automatically uncompress them, and put them in a folder with the same name as the file (but all lowercased).  Here is where they are:

In [50]:
folders = os.listdir(filepath)
# Skip .xslx file, if we are ever able to upload it...
# Currently can't upload due to conflicts with other versions of the dataset on Kaggle.
folders = [f for f in folders if 'xlsx' not in f]
folders

['accepted_2007_to_2018q3.csv', 'rejected_2007_to_2018q3.csv']

In [51]:
os.listdir(filepath + folders[0])

['accepted_2007_to_2018Q3.csv']

In [52]:
acc_folder = filepath + [f for f in folders if 'accepted' in f][0]
accepted_fn = acc_folder + '/' + os.listdir(acc_folder)[0]

rej_folder = filepath + [f for f in folders if 'rejected' in f][0]
rejected_fn = rej_folder + '/' + os.listdir(rej_folder)[0]

accepted_fn

'../input/accepted_2007_to_2018q3.csv/accepted_2007_to_2018Q3.csv'

In [53]:
if os.path.isfile(accepted_fn) and os.path.isfile(rejected_fn):
    print('both paths still point to the actual file; all is good')
else:
    print('Kaggle changed how they handle compressed files again...you need to locate the files')

both paths still point to the actual file; all is good

In [54]:
# Takes a while to read, because these files are large...give it a minute or so
acc_df = pd.read_csv(accepted_fn)

# this is a dataset with rejected loans from lendingclub
rej_df = pd.read_csv(rejected_fn)

/opt/conda/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2785: DtypeWarning: Columns (0,19,49,59,118,129,130,131,134,135,136,139,145,146,147) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [55]:
# this is how we can see how many entries are in the dataframe (df)
# it also works for numpy arrays
acc_df.shape

(2132287, 151)

In [56]:
rej_df.shape

(25054319, 9)

In [70]:
[col for col in acc_df.columns if 'fico' in col.lower()]

['fico_range_low',
 'fico_range_high',
 'last_fico_range_high',
 'last_fico_range_low',
 'sec_app_fico_range_low',
 'sec_app_fico_range_high']

In [71]:
# No fico score in rejected loans
[col for col in rej_df.columns if 'fico' in col.lower()]

[]

In [72]:
rej_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25054319 entries, 0 to 25054318
Data columns (total 9 columns):
Amount Requested        float64
Application Date        object
Loan Title              object
Risk_Score              float64
Debt-To-Income Ratio    object
Zip Code                object
State                   object
Employment Length       object
Policy Code             float64
dtypes: float64(3), object(6)
memory usage: 1.7+ GB

In [73]:
acc_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2132287 entries, 0 to 2132286
Columns: 151 entries, id to settlement_term
dtypes: float64(113), object(38)
memory usage: 2.4+ GB

In [57]:
# this is how many rows pandas will show by default with methods like pd.dataframe.head()
pd.options.display.max_rows

1000

In [58]:
# we want to increase it, because in this case there are a lot of column names
pd.options.display.max_rows = 1000

In [59]:
# the .T is transposing the matrix.
# We do this so the 111 column dataframe is easier to read (easier to scroll down than sideways) 
# .head() shows the first few rows of the data
acc_df.head().T

                                                                                            0                        ...                                                                          4
id                                                                                   93999587                        ...                                                                   96229241
member_id                                                                                 NaN                        ...                                                                        NaN
loan_amnt                                                                               19200                        ...                                                                       5000
funded_amnt                                                                             19200                        ...                                                                       5000
funded_amnt_inv                                                                         19200                        ...                                                                       5000
term                                                                                36 months                        ...                                                                  36 months
int_rate                                                                                13.99                        ...                                                                      10.49
installment                                                                            656.12                        ...                                                                     162.49
grade                                                                                       C                        ...                                                                          B
sub_grade                                                                                  C3                        ...                                                                         B2
emp_title                                                                             Foreman                        ...                                                                     driver
emp_length                                                                          10+ years                        ...                                                                  10+ years
home_ownership                                                                       MORTGAGE                        ...                                                                       RENT
annual_inc                                                                              75000                        ...                                                                      75000
verification_status                                                              Not Verified                        ...                                                               Not Verified
issue_d                                                                              Dec-2016                        ...                                                                   Dec-2016
loan_status                                                                           Current                        ...                                                                    Current
pymnt_plan                                                                                  n                        ...                                                                          n
url                                         https://lendingclub.com/browse/loanDetail.acti...                        ...                          https://lendingclub.com/browse/loanDetail.acti...
desc                                                                                      NaN                        ...                                                                        NaN
purpose                                                                      home_improvement                        ...                                                                      other
title                                                                        Home improvement                        ...                                                                      Other
zip_code                                                                                531xx                        ...                                                                      891xx
addr_state                                                                                 WI                        ...                                                                         NV
dti                                                                                     16.98                        ...                                                                      11.01
delinq_2yrs                                                                                 0                        ...                                                                          0
earliest_cr_line                                                                     Dec-2003                        ...                                                                   Oct-1990
fico_range_low                                                                            740                        ...                                                                        665
fico_range_high                                                                           744                        ...                                                                        669
inq_last_6mths                                                                              0                        ...                                                                          1
mths_since_last_delinq                                                                    NaN                        ...                                                                        NaN
mths_since_last_record                                                                    NaN                        ...                                                                         74
open_acc                                                                                    8                        ...                                                                          4
pub_rec                                                                                     0                        ...                                                                          1
revol_bal                                                                               12802                        ...                                                                       6436
revol_util                                                                               59.8                        ...                                                                       47.3
total_acc                                                                                  12                        ...                                                                          9
initial_list_status                                                                         w                        ...                                                                          f
out_prncp                                                                             7057.74                        ...                                                                    1843.79
out_prncp_inv                                                                         7057.74                        ...                                                                    1843.79
total_pymnt                                                                           15909.6                        ...                                                                    3892.48
total_pymnt_inv                                                                       15909.6                        ...                                                                    3892.48
total_rec_prncp                                                                       12142.3                        ...                                                                    3156.21
total_rec_int                                                                         3767.31                        ...                                                                     736.27
total_rec_late_fee                                                                          0                        ...                                                                          0
recoveries                                                                                  0                        ...                                                                          0
collection_recovery_fee                                                                     0                        ...                                                                          0
last_pymnt_d                                                                         Jan-2019                        ...                                                                   Jan-2019
last_pymnt_amnt                                                                        656.12                        ...                                                                     162.49
next_pymnt_d                                                                         Feb-2019                        ...                                                                   Feb-2019
last_credit_pull_d                                                                   Jan-2019                        ...                                                                   Jan-2019
last_fico_range_high                                                                      739                        ...                                                                        714
last_fico_range_low                                                                       735                        ...                                                                        710
collections_12_mths_ex_med                                                                  0                        ...                                                                          0
mths_since_last_major_derog                                                               NaN                        ...                                                                        NaN
policy_code                                                                                 1                        ...                                                                          1
application_type                                                                   Individual                        ...                                                                 Individual
annual_inc_joint                                                                          NaN                        ...                                                                        NaN
dti_joint                                                                                 NaN                        ...                                                                        NaN
verification_status_joint                                                                 NaN                        ...                                                                        NaN
acc_now_delinq                                                                              0                        ...                                                                          0
tot_coll_amt                                                                                0                        ...                                                                          0
tot_cur_bal                                                                            243746                        ...                                                                      23339
open_acc_6m                                                                                 0                        ...                                                                          0
open_act_il                                                                                 2                        ...                                                                          1
open_il_12m                                                                                 0                        ...                                                                          0
open_il_24m                                                                                 2                        ...                                                                          0
mths_since_rcnt_il                                                                         15                        ...                                                                         40
total_bal_il                                                                             6341                        ...                                                                      16903
il_util                                                                                    39                        ...                                                                         50
open_rv_12m                                                                                 0                        ...                                                                          1
open_rv_24m                                                                                 0                        ...                                                                          1
max_bal_bc                                                                               4126                        ...                                                                       3848
all_util                                                                                   57                        ...                                                                         50
total_rev_hi_lim                                                                        21400                        ...                                                                      13600
inq_fi                                                                                      0                        ...                                                                          0
total_cu_tl                                                                                 0                        ...                                                                          0
inq_last_12m                                                                                0                        ...                                                                          1
acc_open_past_24mths                                                                        3                        ...                                                                          1
avg_cur_bal                                                                             30468                        ...                                                                       7780
bc_open_to_buy                                                                           7136                        ...                                                                       7164
bc_util                                                                                  53.4                        ...                                                                       47.3
chargeoff_within_12_mths                                                                    0                        ...                                                                          0
delinq_amnt                                                                                 0                        ...                                                                          0
mo_sin_old_il_acct                                                                        111                        ...                                                                         40
mo_sin_old_rev_tl_op                                                                       80                        ...                                                                        314
mo_sin_rcnt_rev_tl_op                                                                      26                        ...                                                                         10
mo_sin_rcnt_tl                                                                             15                        ...                                                                         10
mort_acc                                                                                    3                        ...                                                                          1
mths_since_recent_bc                                                                       47                        ...                                                                         10
mths_since_recent_bc_dlq                                                                  NaN                        ...                                                                        NaN
mths_since_recent_inq                                                                      15                        ...                                                                          3
mths_since_recent_revol_delinq                                                            NaN                        ...                                                                        NaN
num_accts_ever_120_pd                                                                       0                        ...                                                                          0
num_actv_bc_tl                                                                              2                        ...                                                                          2
num_actv_rev_tl                                                                             3                        ...                                                                          2
num_bc_sats                                                                                 2                        ...                                                                          2
num_bc_tl                                                                                   2                        ...                                                                          4
num_il_tl                                                                                   3                        ...                                                                          1
num_op_rev_tl                                                                               3                        ...                                                                          3
num_rev_accts                                                                               4                        ...                                                                          7

In [60]:
# .tail() shows the last few rows
acc_df.tail().T

                                                                                      2132282                       ...                                                                 2132286
id                                                                                  125893755                       ...                         Total amount funded in policy code 2: 564202131
member_id                                                                                 NaN                       ...                                                                     NaN
loan_amnt                                                                                6000                       ...                                                                     NaN
funded_amnt                                                                              6000                       ...                                                                     NaN
funded_amnt_inv                                                                          6000                       ...                                                                     NaN
term                                                                                36 months                       ...                                                                     NaN
int_rate                                                                                10.91                       ...                                                                     NaN
installment                                                                            196.18                       ...                                                                     NaN
grade                                                                                       B                       ...                                                                     NaN
sub_grade                                                                                  B4                       ...                                                                     NaN
emp_title                                                                       Truck Driver                        ...                                                                     NaN
emp_length                                                                          10+ years                       ...                                                                     NaN
home_ownership                                                                       MORTGAGE                       ...                                                                     NaN
annual_inc                                                                              50000                       ...                                                                     NaN
verification_status                                                           Source Verified                       ...                                                                     NaN
issue_d                                                                              Jan-2018                       ...                                                                     NaN
loan_status                                                                           Current                       ...                                                                     NaN
pymnt_plan                                                                                  n                       ...                                                                     NaN
url                                         https://lendingclub.com/browse/loanDetail.acti...                       ...                                                                     NaN
desc                                                                                      NaN                       ...                                                                     NaN
purpose                                                                    debt_consolidation                       ...                                                                     NaN
title                                                                      Debt consolidation                       ...                                                                     NaN
zip_code                                                                                038xx                       ...                                                                     NaN
addr_state                                                                                 NH                       ...                                                                     NaN
dti                                                                                     28.93                       ...                                                                     NaN
delinq_2yrs                                                                                 0                       ...                                                                     NaN
earliest_cr_line                                                                     Jun-1997                       ...                                                                     NaN
fico_range_low                                                                            690                       ...                                                                     NaN
fico_range_high                                                                           694                       ...                                                                     NaN
inq_last_6mths                                                                              0                       ...                                                                     NaN
mths_since_last_delinq                                                                     58                       ...                                                                     NaN
mths_since_last_record                                                                    NaN                       ...                                                                     NaN
open_acc                                                                                   11                       ...                                                                     NaN
pub_rec                                                                                     0                       ...                                                                     NaN
revol_bal                                                                                6950                       ...                                                                     NaN
revol_util                                                                               51.9                       ...                                                                     NaN
total_acc                                                                                  14                       ...                                                                     NaN
initial_list_status                                                                         w                       ...                                                                     NaN
out_prncp                                                                             4212.83                       ...                                                                     NaN
out_prncp_inv                                                                         4212.83                       ...                                                                     NaN
total_pymnt                                                                           2350.52                       ...                                                                     NaN
total_pymnt_inv                                                                       2350.52                       ...                                                                     NaN
total_rec_prncp                                                                       1787.17                       ...                                                                     NaN
total_rec_int                                                                          563.35                       ...                                                                     NaN
total_rec_late_fee                                                                          0                       ...                                                                     NaN
recoveries                                                                                  0                       ...                                                                     NaN
collection_recovery_fee                                                                     0                       ...                                                                     NaN
last_pymnt_d                                                                         Jan-2019                       ...                                                                     NaN
last_pymnt_amnt                                                                        196.18                       ...                                                                     NaN
next_pymnt_d                                                                         Feb-2019                       ...                                                                     NaN
last_credit_pull_d                                                                   Jan-2019                       ...                                                                     NaN
last_fico_range_high                                                                      824                       ...                                                                     NaN
last_fico_range_low                                                                       820                       ...                                                                     NaN
collections_12_mths_ex_med                                                                  0                       ...                                                                     NaN
mths_since_last_major_derog                                                                58                       ...                                                                     NaN
policy_code                                                                                 1                       ...                                                                     NaN
application_type                                                                   Individual                       ...                                                                     NaN
annual_inc_joint                                                                          NaN                       ...                                                                     NaN
dti_joint                                                                                 NaN                       ...                                                                     NaN
verification_status_joint                                                                 NaN                       ...                                                                     NaN
acc_now_delinq                                                                              0                       ...                                                                     NaN
tot_coll_amt                                                                                0                       ...                                                                     NaN
tot_cur_bal                                                                            230614                       ...                                                                     NaN
open_acc_6m                                                                                 0                       ...                                                                     NaN
open_act_il                                                                                 1                       ...                                                                     NaN
open_il_12m                                                                                 1                       ...                                                                     NaN
open_il_24m                                                                                 1                       ...                                                                     NaN
mths_since_rcnt_il                                                                          9                       ...                                                                     NaN
total_bal_il                                                                            18497                       ...                                                                     NaN
il_util                                                                                    83                       ...                                                                     NaN
open_rv_12m                                                                                 1                       ...                                                                     NaN
open_rv_24m                                                                                 1                       ...                                                                     NaN
max_bal_bc                                                                               2257                       ...                                                                     NaN
all_util                                                                                   71                       ...                                                                     NaN
total_rev_hi_lim                                                                        13400                       ...                                                                     NaN
inq_fi                                                                                      1                       ...                                                                     NaN
total_cu_tl                                                                                 0                       ...                                                                     NaN
inq_last_12m                                                                                2                       ...                                                                     NaN
acc_open_past_24mths                                                                        2                       ...                                                                     NaN
avg_cur_bal                                                                             20965                       ...                                                                     NaN
bc_open_to_buy                                                                           5850                       ...                                                                     NaN
bc_util                                                                                  54.3                       ...                                                                     NaN
chargeoff_within_12_mths                                                                    0                       ...                                                                     NaN
delinq_amnt                                                                                 0                       ...                                                                     NaN
mo_sin_old_il_acct                                                                          9                       ...                                                                     NaN
mo_sin_old_rev_tl_op                                                                      246                       ...                                                                     NaN
mo_sin_rcnt_rev_tl_op                                                                       7                       ...                                                                     NaN
mo_sin_rcnt_tl                                                                              7                       ...                                                                     NaN
mort_acc                                                                                    2                       ...                                                                     NaN
mths_since_recent_bc                                                                       45                       ...                                                                     NaN
mths_since_recent_bc_dlq                                                                   58                       ...                                                                     NaN
mths_since_recent_inq                                                                       7                       ...                                                                     NaN
mths_since_recent_revol_delinq                                                             58                       ...                                                                     NaN
num_accts_ever_120_pd                                                                       1                       ...                                                                     NaN
num_actv_bc_tl                                                                              8                       ...                                                                     NaN
num_actv_rev_tl                                                                             8                       ...                                                                     NaN
num_bc_sats                                                                                 8                       ...                                                                     NaN
num_bc_tl                                                                                   9                       ...                                                                     NaN
num_il_tl                                                                                   1                       ...                                                                     NaN
num_op_rev_tl                                                                               9                       ...                                                                     NaN
num_rev_accts                                                                              11                       ...                                                                     NaN
num_rev_tl_bal_gt_0                                                                         8                       ...                                                                     NaN
num_sats                                                                                   11                       ...                                                                     NaN

In [61]:
# .info() tells us the datatype(int64, `object` is a string)
# and will also tell us the number of non-null (not missing) data points for each column
# because this dataframe is so large, we have to force it to show the datatypes and non-null numbers with the arguments
acc_df.info(verbose=True, null_counts=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2132287 entries, 0 to 2132286
Data columns (total 151 columns):
id                                            2132287 non-null object
member_id                                     0 non-null float64
loan_amnt                                     2132256 non-null float64
funded_amnt                                   2132256 non-null float64
funded_amnt_inv                               2132256 non-null float64
term                                          2132256 non-null object
int_rate                                      2132256 non-null float64
installment                                   2132256 non-null float64
grade                                         2132256 non-null object
sub_grade                                     2132256 non-null object
emp_title                                     1986234 non-null object
emp_length                                    1997053 non-null object
home_ownership                                2132256 non-null object
annual_inc                                    2132252 non-null float64
verification_status                           2132256 non-null object
issue_d                                       2132256 non-null object
loan_status                                   2132256 non-null object
pymnt_plan                                    2132256 non-null object
url                                           2132256 non-null object
desc                                          126067 non-null object
purpose                                       2132256 non-null object
title                                         2108931 non-null object
zip_code                                      2132255 non-null object
addr_state                                    2132256 non-null object
dti                                           2130782 non-null float64
delinq_2yrs                                   2132227 non-null float64
earliest_cr_line                              2132227 non-null object
fico_range_low                                2132256 non-null float64
fico_range_high                               2132256 non-null float64
inq_last_6mths                                2132226 non-null float64
mths_since_last_delinq                        1045950 non-null float64
mths_since_last_record                        343706 non-null float64
open_acc                                      2132227 non-null float64
pub_rec                                       2132227 non-null float64
revol_bal                                     2132256 non-null float64
revol_util                                    2130610 non-null float64
total_acc                                     2132227 non-null float64
initial_list_status                           2132256 non-null object
out_prncp                                     2132256 non-null float64
out_prncp_inv                                 2132256 non-null float64
total_pymnt                                   2132256 non-null float64
total_pymnt_inv                               2132256 non-null float64
total_rec_prncp                               2132256 non-null float64
total_rec_int                                 2132256 non-null float64
total_rec_late_fee                            2132256 non-null float64
recoveries                                    2132256 non-null float64
collection_recovery_fee                       2132256 non-null float64
last_pymnt_d                                  2129992 non-null object
last_pymnt_amnt                               2132256 non-null float64
next_pymnt_d                                  865638 non-null object
last_credit_pull_d                            2132182 non-null object
last_fico_range_high                          2132256 non-null float64
last_fico_range_low                           2132256 non-null float64
collections_12_mths_ex_med                    2132111 non-null float64
mths_since_last_major_derog                   551595 non-null float64
policy_code                                   2132256 non-null float64
application_type                              2132256 non-null object
annual_inc_joint                              103928 non-null float64
dti_joint                                     103924 non-null float64
verification_status_joint                     100882 non-null object
acc_now_delinq                                2132227 non-null float64
tot_coll_amt                                  2061980 non-null float64
tot_cur_bal                                   2061980 non-null float64
open_acc_6m                                   1266126 non-null float64
open_act_il                                   1266127 non-null float64
open_il_12m                                   1266127 non-null float64
open_il_24m                                   1266127 non-null float64
mths_since_rcnt_il                            1226810 non-null float64
total_bal_il                                  1266127 non-null float64
il_util                                       1083680 non-null float64
open_rv_12m                                   1266127 non-null float64
open_rv_24m                                   1266127 non-null float64
max_bal_bc                                    1266127 non-null float64
all_util                                      1265945 non-null float64
total_rev_hi_lim                              2061980 non-null float64
inq_fi                                        1266127 non-null float64
total_cu_tl                                   1266126 non-null float64
inq_last_12m                                  1266126 non-null float64
acc_open_past_24mths                          2082226 non-null float64
avg_cur_bal                                   2061923 non-null float64
bc_open_to_buy                                2059012 non-null float64
bc_util                                       2057939 non-null float64
chargeoff_within_12_mths                      2132111 non-null float64
delinq_amnt                                   2132227 non-null float64
mo_sin_old_il_acct                            1997663 non-null float64
mo_sin_old_rev_tl_op                          2061979 non-null float64
mo_sin_rcnt_rev_tl_op                         2061979 non-null float64
mo_sin_rcnt_tl                                2061980 non-null float64
mort_acc                                      2082226 non-null float64
mths_since_recent_bc                          2060435 non-null float64
mths_since_recent_bc_dlq                      494532 non-null float64
mths_since_recent_inq                         1852868 non-null float64
mths_since_recent_revol_delinq                703577 non-null float64
num_accts_ever_120_pd                         2061980 non-null float64
num_actv_bc_tl                                2061980 non-null float64
num_actv_rev_tl                               2061980 non-null float64
num_bc_sats                                   2073666 non-null float64
num_bc_tl                                     2061980 non-null float64
num_il_tl                                     2061980 non-null float64
num_op_rev_tl                                 2061980 non-null float64
num_rev_accts                                 2061979 non-null float64
num_rev_tl_bal_gt_0                           2061980 non-null float64
num_sats                                      2073666 non-null float64
num_tl_120dpd_2m                              1981458 non-null float64
num_tl_30dpd                                  2061980 non-null float64
num_tl_90g_dpd_24m                            2061980 non-null float64
num_tl_op_past_12m                            2061980 non-null float64
pct_tl_nvr_dlq                                2061825 non-null float64
percent_bc_gt_75                              2058569 non-null float64
pub_rec_bankruptcies                          2130891 non-null float64
tax_liens                                     2132151 non-null float64
tot_hi_cred_lim                               2061980 non-null float64
total_bal_ex_mort                             2082226 non-null float64
total_bc_limit                                2082226 non-null float64
total_il_high_credit_limit                    2061980 non-null float64
revol_bal_joint                               91238 non-null float64
sec_app_fico_range_low                        91239 non-null float64
sec_app_fico_range_high                       91239 non-null float64
sec_app_earliest_cr_line                      91239 non-null object
sec_app_inq_last_6mths                        91239 non-null float64
sec_app_mort_acc                              91239 non-null float64
sec_app_open_acc                              91239 non-null float64
sec_app_revol_util                            89660 non-null float64
sec_app_open_act_il                           91239 non-null float64
sec_app_num_rev_accts                         91239 non-null float64
sec_app_chargeoff_within_12_mths              91239 non-null float64
sec_app_collections_12_mths_ex_med            91239 non-null float64
sec_app_mths_since_last_major_derog           30788 non-null float64
hardship_flag                                 2132256 non-null object
hardship_type                                 10316 non-null object
hardship_reason                               10316 non-null object
hardship_status                               10316 non-null object
deferral_term                                 10316 non-null float64
hardship_amount                               10316 non-null float64
hardship_start_date                           10316 non-null object
hardship_end_date                             10316 non-null object
payment_plan_start_date                       10316 non-null object
hardship_length                               10316 non-null float64
hardship_dpd                                  10316 non-null float64
hardship_loan_status                          10316 non-null object
orig_projected_additional_accrued_interest    8221 non-null float64
hardship_payoff_balance_amount                10316 non-null float64
hardship_last_payment_amount                  10316 non-null float64
disbursement_method                           2132256 non-null object
debt_settlement_flag                          2132256 non-null object
debt_settlement_flag_date                     31493 non-null object
settlement_status                             31493 non-null object
settlement_date                               31493 non-null object
settlement_amount                             31493 non-null float64
settlement_percentage                         31493 non-null float64
settlement_term                               31493 non-null float64
dtypes: float64(113), object(38)
memory usage: 2.4+ GB

# Some common pandas functions

We find ourselves doing the same types of things often in pandas.  For example, masking.  

## Masking dataframes

Maybe we only want to see one column.  We do this like

`acc_df['int_rate']`

We can also subset a dataframe based on some critereon.  Let's look at only the highest interest rates

`acc_df[acc_df['int_rate'] > 20]`

We can take the mean, median, get the standard deviation of columns:

`acc_df['int_rate'].mean()`

In [ ]:
# shows some common summary statistics
# again, transposing with .T to make it easier to read
acc_df.describe().T

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import re
# "magic" command to make plots show up in the notebook
%matplotlib inline

In [ ]:
acc_df[acc_df['int_rate'] > 20]['int_rate'].mean()
# thats a bit of a complicated statement.  Breaking it down:
# acc_df['int_rate'] > 20 returns a mask: an array of True/False values
# putting this array into acc_df[] returns the dataframe rows where the interest rates are greater than 20

# so this first part: acc_df[acc_df['int_rate'] > 20]
# gives us a dataframe

# we select a column with ['int_rate'] at the end.  Then we get the average value with .mean()

## Finding unique values

Numpy has a function for finding the unique values in an array:

np.unique(array)

This is built into pandas:

acc_df['grade'].unique()

shows us the unique values in that column.

In [ ]:
acc_df['grade'].unique()

In [ ]:
# selecting only grade A loans:
acc_df[acc_df['grade'] == 'A'].describe().T

In [ ]:
acc_df['loan_status'].unique()

In [ ]:
# looking at only defaulted loans:
default_categories = ['Default', 'Charged Off', 'Does not meet the credit policy. Status:Charged Off']
# .isin() is a trick for checking if something is in a list
# it's a pandas-specific function
acc_df[acc_df['loan_status'].isin(default_categories)].describe().T
# check out the average interest rate and dti (debt-to-income)

In [ ]:
# Seaborn is a recently-created Python library for easily making nice-looking plots
# You will have to install it with `conda install seaborn` or `pip install seaborn`, etc

# The docs are here for this function: http://seaborn.pydata.org/generated/seaborn.distplot.html
# Found by Googling 'seaborn histogram'
# Need to drop missing values, otherwise throws an error
# It would be better to impute missing values.
f = sns.distplot(acc_df['dti'].dropna())

In [ ]:
# outliers are screwing up the histogram... remove them
# adapted from http://stackoverflow.com/questions/11686720/is-there-a-numpy-builtin-to-reject-outliers-from-a-list
# we're using interquartile range to determine outliers
def reject_outliers(sr, iq_range=0.5, side='left', return_mask=False):
    """
    Takes an array (or pandas series) and returns an array with outliers excluded, according to the
    interquartile range.
    
    Parameters:
    -----------
    sr: array
        array of numeric values
    iq_range: float
        percent to calculate quartiles by, 0.5 will yield 25% and 75%ile quartiles
    side: string
        if 'left', will return everything below the highest quartile
        if 'right', will return everything above the lowest quartile
        if 'both', will return everything between the high and low quartiles
    """
    pcnt = (1 - iq_range) / 2
    qlow, median, qhigh = sr.dropna().quantile([pcnt, 0.50, 1-pcnt])
    iqr = qhigh - qlow
    if side=='both':
        mask = (sr - median).abs() <= iqr
    elif side=='left':
        mask = (sr - median) <= iqr
    elif side=='right':
        mask = (sr - median) >= iqr
    else:
        print('options for side are left, right, or both')
    
    if return_mask:
        return mask
    
    return sr[mask]

In [ ]:
# sweeeeeeeetttt....
dti_no_outliers = reject_outliers(acc_df['dti'], iq_range=0.85) # arrived at 0.85 via trial and error
f = sns.distplot(dti_no_outliers)
# other types of plot examples:
# http://seaborn.pydata.org/examples/

In [ ]:
# sets the xkcd style if you want to make the plots look funny...may neet to install some fonts
plt.xkcd()

In [ ]:
f = sns.distplot(dti_no_outliers)

In [ ]:
# back to default
import matplotlib as mpl
mpl.rcParams.update(mpl.rcParamsDefault)

In [ ]:
f = sns.distplot(dti_no_outliers)

In [ ]:
# other styles:
# http://matplotlib.org/users/style_sheets.html
# this is the R ggplot style, which some people really like
plt.style.use('ggplot')

In [ ]:
# http://seaborn.pydata.org/generated/seaborn.regplot.html
# takes a long time because there are a lot of points, but works for smaller datasets
# f = sns.regplot(data=acc_df, x='dti', y='int_rate', fit_reg=False)
# instead, lets make a heatmap:
# http://stackoverflow.com/questions/2369492/generate-a-heatmap-in-matplotlib-using-a-scatter-data-set
# http://seaborn.pydata.org/generated/seaborn.jointplot.html
mask = reject_outliers(acc_df['dti'], iq_range=0.85, return_mask=True)
f = sns.jointplot(data=acc_df.ix[mask, :], x='dti', y='int_rate', kind='hex', joint_kws=dict(gridsize=50))